In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
csv_path = "neo.csv"
neo_df = pd.read_csv(csv_path)
neo_df.head()

,date,AdrActCnt,BlkCnt,BlkSizeByte,BlkSizeMeanByte,CapMrktCurUSD,FeeMeanUSD,FeeMedUSD,FeeTotUSD,IssContNtv,...,TxTfrValAdjUSD,TxTfrValMeanNtv,TxTfrValMeanUSD,TxTfrValMedNtv,TxTfrValMedUSD,TxTfrValNtv,TxTfrValUSD,VtyDayRet180d,VtyDayRet30d,VtyDayRet60d
0,2016-07-15,1,1,401,401.0,NaN,NaN,NaN,NaN,0,...,NaN,100000000.0,NaN,100000000.0,NaN,100000000,NaN,NaN,NaN,NaN
1,2016-07-16,0,0,0,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
2,2016-07-17,0,0,0,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
3,2016-07-18,0,0,0,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
4,2016-07-19,0,0,0,NaN,NaN,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN

In [3]:
clean_neo_df = neo_df.dropna(how="any")
clean_neo_df.head()

,date,AdrActCnt,BlkCnt,BlkSizeByte,BlkSizeMeanByte,CapMrktCurUSD,FeeMeanUSD,FeeMedUSD,FeeTotUSD,IssContNtv,...,TxTfrValAdjUSD,TxTfrValMeanNtv,TxTfrValMeanUSD,TxTfrValMedNtv,TxTfrValMedUSD,TxTfrValNtv,TxTfrValUSD,VtyDayRet180d,VtyDayRet30d,VtyDayRet60d
730,2018-07-15,4599,4021,9313023,2316.096245,3.348216e+09,0.000055,0.0,1.319079,0,...,4.166956e+07,379.720484,12713.863155,20.0,669.643260,3229143,1.081187e+08,0.070371,0.060235,0.058201
731,2018-07-16,5738,4087,12947523,3167.977245,3.684568e+09,0.163637,0.0,5851.676872,0,...,5.003499e+07,382.750937,14102.717566,18.0,663.222194,3677471,1.354989e+08,0.070792,0.062934,0.059261
732,2018-07-17,8568,3947,28550662,7233.509501,3.929847e+09,0.000006,0.0,0.576344,0,...,2.320172e+08,713.952385,28057.238793,30.0,1178.954202,9206416,3.617981e+08,0.070995,0.064008,0.059724
733,2018-07-18,6705,4071,21907019,5381.237779,3.761783e+09,0.000260,0.0,18.752287,0,...,1.171274e+08,596.287165,22431.028525,20.0,752.356577,6810792,2.562072e+08,0.071035,0.064361,0.059911
734,2018-07-19,5244,4000,14280528,3570.132000,3.588916e+09,0.000066,0.0,2.684663,0,...,6.190919e+07,454.218923,16301.533787,18.0,646.004808,4191078,1.504143e+08,0.070858,0.064850,0.059176

In [4]:
clean_neo_df.reset_index()

,index,date,AdrActCnt,BlkCnt,BlkSizeByte,BlkSizeMeanByte,CapMrktCurUSD,FeeMeanUSD,FeeMedUSD,FeeTotUSD,...,TxTfrValAdjUSD,TxTfrValMeanNtv,TxTfrValMeanUSD,TxTfrValMedNtv,TxTfrValMedUSD,TxTfrValNtv,TxTfrValUSD,VtyDayRet180d,VtyDayRet30d,VtyDayRet60d
0,730,2018-07-15,4599,4021,9313023,2316.096245,3.348216e+09,0.000055,0.0,1.319079,...,4.166956e+07,379.720484,12713.863155,20.0,669.643260,3229143,1.081187e+08,0.070371,0.060235,0.058201
1,731,2018-07-16,5738,4087,12947523,3167.977245,3.684568e+09,0.163637,0.0,5851.676872,...,5.003499e+07,382.750937,14102.717566,18.0,663.222194,3677471,1.354989e+08,0.070792,0.062934,0.059261
2,732,2018-07-17,8568,3947,28550662,7233.509501,3.929847e+09,0.000006,0.0,0.576344,...,2.320172e+08,713.952385,28057.238793,30.0,1178.954202,9206416,3.617981e+08,0.070995,0.064008,0.059724
3,733,2018-07-18,6705,4071,21907019,5381.237779,3.761783e+09,0.000260,0.0,18.752287,...,1.171274e+08,596.287165,22431.028525,20.0,752.356577,6810792,2.562072e+08,0.071035,0.064361,0.059911
4,734,2018-07-19,5244,4000,14280528,3570.132000,3.588916e+09,0.000066,0.0,2.684663,...,6.190919e+07,454.218923,16301.533787,18.0,646.004808,4191078,1.504143e+08,0.070858,0.064850,0.059176
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
473,1203,2019-10-31,1984,5199,8510902,1637.026736,1.057385e+09,0.000409,0.0,8.583824,...,9.942499e+07,2215.912930,23430.726551,44.0,465.249313,10179904,1.076408e+08,0.058645,0.062980,0.053572
474,1204,2019-11-01,1835,5107,7010312,1372.686900,1.063271e+09,0.000445,0.0,7.604066,...,1.406289e+08,4805.367375,51094.056095,55.0,584.798802,17174383,1.826102e+08,0.058624,0.062970,0.053356
475,1205,2019-11-02,2043,5120,7035837,1374.186914,1.099188e+09,0.000526,0.0,8.822768,...,7.156449e+07,1800.399221,19789.763426,41.0,450.666880,7396040,8.129635e+07,0.058668,0.062454,0.053475
476,1206,2019-11-03,1825,5117,7249299,1416.708814,1.106608e+09,0.000341,0.0,6.079679,...,1.058825e+08,3267.430364,36157.643024,39.0,431.577087,10416568,1.152706e+08,0.058650,0.062440,0.053340
477,1207,2019-11-04,2316,5146,8884653,1726.516323,1.143310e+09,0.000422,0.0,9.488646,...,7.636734e+07,1606.767686,18370.330946,42.0,480.190078,7358996,8.413612e+07,0.058696,0.062444,0.053459

In [5]:
# export to csv 
clean_neo_df.to_csv("clean_neo_df.csv")

PermissionError: [Errno 13] Permission denied: 'clean_neo_df.csv'

In [6]:
clean_neo_df = clean_neo_df.drop(clean_neo_df.index[384:479])

In [7]:
organized_neo_df = clean_neo_df[["date", "CapMrktCurUSD", "PriceUSD"]]
organized_neo_df.head()

           date  CapMrktCurUSD   PriceUSD
730  2018-07-15   3.348216e+09  33.482163
731  2018-07-16   3.684568e+09  36.845677
732  2018-07-17   3.929847e+09  39.298473
733  2018-07-18   3.761783e+09  37.617829
734  2018-07-19   3.588916e+09  35.889156

In [8]:
organized_neo_number = organized_neo_df['CapMrktCurUSD'].div(organized_neo_df['PriceUSD'])
organized_neo_df['number_of_coins'] = organized_neo_number
organized_neo_df.head()

C:\Users\murth\Anaconda3\envs\pyData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

           date  CapMrktCurUSD   PriceUSD  number_of_coins
730  2018-07-15   3.348216e+09  33.482163      100000000.0
731  2018-07-16   3.684568e+09  36.845677      100000000.0
732  2018-07-17   3.929847e+09  39.298473      100000000.0
733  2018-07-18   3.761783e+09  37.617829      100000000.0
734  2018-07-19   3.588916e+09  35.889156      100000000.0

In [9]:
organized_neo_df = organized_neo_df.rename(
    columns={"date": "Date", "marketcap_usd": "Market Cap (USD)", "price_usd": "Price (USD)", "number_of_coins": "Number of Coins"})
organized_neo_df.head()

           Date  CapMrktCurUSD   PriceUSD  Number of Coins
730  2018-07-15   3.348216e+09  33.482163      100000000.0
731  2018-07-16   3.684568e+09  36.845677      100000000.0
732  2018-07-17   3.929847e+09  39.298473      100000000.0
733  2018-07-18   3.761783e+09  37.617829      100000000.0
734  2018-07-19   3.588916e+09  35.889156      100000000.0

In [10]:
count = organized_neo_df["Date"].count()
print(count)

384

In [11]:
organized_neo_df.to_csv("organized_neo_df.csv")

In [12]:
connection_string = "postgres:postgres@localhost:5432/test_db"
engine = create_engine(f'postgresql://{connection_string}')

In [13]:
engine.table_names()

OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"

(Background on this error at: http://sqlalche.me/e/e3q8)